apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    name: aspapp
spec:
  containers:
  - name: asp-container
    image: fluentapimodelmappingtodatabase:v1
    resources:
    ports:
      - containerPort: 80
    env:
      - name: DB_CONNECTION
        value: "Data Source=mssql-service, 31433;Initial Catalog=FluentApi;Persist Security Info=True;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=True;"

---

kind: Service
apiVersion: v1
metadata:
  name:  aspapp-service
spec:
  selector:
    name:  aspapp
  type:   NodePort
  ports:
  - name:  name-of-the-port
    port:  80
    nodePort:  30080
